services:
  # Backend API service
  - type: web
    name: fastapi-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ENV
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /health
    
  # Frontend static site
  - type: web
    name: react-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    rootDir: frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://fastapi-backend.onrender.com