# Alternative: Backend-specific Render configuration
services:
  - type: web
    name: website-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENV
        value: production
    healthCheckPath: /health